version: "3"
services:
  notes-app-container:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./build/src:/app/src:ro
      - /app/node_modules
    environment:
      - NODE_ENV=Development
      - MONGO_USER=Piero95
      - MONGO_PASSWORD=j95p250a
      - SESSION_SECRET=top-secret
    command: yarn run dev
