version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - notes-app-container
  notes-app-container:
    build: .
    image: piero95/tarea-1-programacion-ute-notes-app-container
    depends_on:
      - mongo-container
  mongo-container:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Piero95
      - MONGO_INITDB_ROOT_PASSWORD=j95p250a
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: